### ISSUE TITLE
Interest in TTC, but repo empty

### ISSUE THREAD

**Issue by dehann** [aamini/TimeToContact.jl#1]
Hi @aamini I found your paper on archive and interested in the FastConv and TTC implementations. I'm having a little trouble finding the code. Is the code available anywhere, or maybe consider making public and the community in time might fork and help develop. Thanks!

**Comment by aamini** [comment]
Thanks for pointing this out @dehann ! Must have forgotten to make it public after submitting the paper.

Will update both repos within the next few days!

**Comment by aamini** [comment]
The main parts of the code (for both) should be up now @dehann --  please let me know if you have any questions. I'll try to add simple examples and test cases as well in the coming weeks.
