### ISSUE TITLE
Downsampling

### ISSUE THREAD

**Issue by EasonSun** [aamini/TimeToContact.jl#2]
Hi Alex, thank you for this work! 

I saw in your paper you mentioned downsampling. Is it achieved in the code by `restrict`? Is this function does 2-fold downsampling?

**Comment by aamini** [comment]
Yes, that's correct. 

`img2 = restrict(img1)` takes an image `img1` of size N x M and downsamples the two-fold along each requested axis. The result is `img2` which has size N/2 x M/2. 

Depending on where in the algorithm this function is called, you might notice that it is also accompanied with a call to `uniformBlur`, which preprocesses the image by convolving it with a 2-dimensional box-step function.
